{{- if and (not .Values.maxmind.existingSecret) (or .Values.maxmind.accountId .Values.maxmind.licenseKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoip-authz.fullname" . }}
  labels:
    {{- include "geoip-authz.labels" . | nindent 4 }}
type: Opaque
stringData:
  GEOIP_ACCOUNT_ID: {{ .Values.maxmind.accountId | quote }}
  GEOIP_LICENSE_KEY: {{ .Values.maxmind.licenseKey | quote }}
{{- end }}
