apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoip-authz.fullname" . }}
  labels:
    {{- include "geoip-authz.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "geoip-authz.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
